language: java
jdk:
- oraclejdk7
before_install:
- chmod +x gradlew
deploy:
  provider: s3
  access_key_id: AKIAI6FGWB26WLJZHBRQ
  secret_access_key:
    secure: V6LtYfj+HXk3iKxK9oEtk7XmHTczwy7gGkIphJOGTAfmz7MtggHC43NDUpRkYdlmxOlOPEbyxaEOOSIyCWipYqak0AUWesWUpTHsnKnmRzOOb+f9srXEBzreAj452zCxgVj5EHdXaC5c/D2N/0ipwqPrOyzMHRMu3gkKy1vvjAo=
  bucket: klib.io
  local-dir: '"/home/travis/build/peterkir/klib.io"'
  upload-dir: artifacts/$TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER
  acl: public_read
  on:
    repo: peterkir/klib.io
