language: java

jdk:
  - oraclejdk7

before_install:
 - chmod +x gradlew

 
env:
   global:
      - "ARTIFACTS_AWS_REGION=frankfurt"
      - "ARTIFACTS_S3_BUCKET=klib.io"
      - secure: ".......long encrypted string............."
      - secure: ".......another long encrypted string....."

before_script:
   - "gem install travis-artifacts"
   
after_script:
  - "travis-artifacts upload --path logs --path a/long/nested/path:short_alias"

  after_failure: # this will of course run only on failure
  - "travis-artifacts upload --path debug/debug.log"

  after_success: # and this only on success
  - "travis-artifacts upload --path build/build.tar.gz"

after_test:
  - "travis-artifacts upload --target-path artifacts/$TRAVIS_BUILD_ID/$TRAVIS_JOB_ID" 