language: java
jdk:
- oraclejdk7
before_install:
- chmod +x gradlew
deploy:
  provider: s3
  access_key_id: AKIAI6FGWB26WLJZHBRQ
  secret_access_key:
    secure: g5+fYcWViFqKZ15/HUYaxGtmFAVxPw3h4UomNZegt++3dgN2yIahUSPtNtsy0qVlZ5UNSHkzMSnQNMMDQXP0EhvAgHHloZxligd/NZk/hWOoQLekS+eFm4gTMZj9MEK7hTDLsbWVPAry2MRZmQWNuorlQWoj+T/CB4ojSpOm1Sg=
  bucket: klib.io
  region: eu-west-1
  local-dir: "/home/travis/build/peterkir/klib.io"
  upload-dir: artifacts/$TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER
  skip_cleanup: true
  acl: public_read
  on:
    repo: peterkir/klib.io
