version: '{build}'
clone_depth: 10
environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.7.0
  TERM: dumb
install:
- gradlew.bat --version
cache: C:\Users\appveyor\.gradle
build_script:
- gradlew.bat --continue
